name: Security

on:
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
        continue-on-error: true
  bandit:
    name: bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install bandit
        run: pip install bandit
      - name: Run bandit (risk-lib and risk-svc)
        run: |
          bandit -q -r packages/risk-lib apps/risk-svc -s B101
